name: Latest blog post
on:
    schedule:
        - cron: "00 24 * * *"
    workflow_dispatch:
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                  max_post_count: "5"
                  feed_list: "https://medium.com/feed/@valerietsai1006"

# 參考網址 : 
# https://molly1024.medium.com/%E4%BD%BF%E7%94%A8%E8%85%B3%E6%9C%AC%E8%87%AA%E5%8B%95%E6%9B%B4%E6%96%B0github-profile-%E4%BB%A5%E6%9B%B4%E6%96%B0medium%E6%9C%80%E6%96%B0%E6%96%87%E7%AB%A0%E7%82%BA%E4%BE%8B-b625dd6fa935